spring:
  banner:
    location: classpath:banner.txt
  http:
    encoding:
      charset: UTF-8
      enabled: "true"
  datasource:
    url: jdbc:h2:mem:lunch_voting
    password: ""
    schema: classpath:/db/schema.sql
    data: classpath:/db/data.sql
    sql-script-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: "false"
    properties:
      hibernate:
        format_sql: "true"
    open-in-view: "false"